const SCREENS = {
  MAIN: 'MAIN_SCREEN',
  HOME: 'HOME_SCREEN',
  PROMOTION: 'PROMOTION_SCREEN',
  KPI: 'KPI_SCREEN',
  REPORT: 'REPORT_SCREEN',
  PROFILE: 'PROFILE_SCREEN',
  LOGIN: 'LOGIN_SCREEN',
  SIGNUP: 'SIGNUP_SCREEN',
};

export default SCREENS;
